# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Error_Box.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


import sys

class Ui_Not_Found(object):
    def setupUi(self, Not_Found):
        Not_Found.setObjectName("Not_Found")
        Not_Found.resize(324, 139)
        Not_Found.setStyleSheet("background-color: rgb(0, 0, 0);")

        Not_Found.setWindowFlag(Qt.FramelessWindowHint) ### ------ FRAMELESS WINDOW LINE
        self.verticalLayoutWidget = QtWidgets.QWidget(Not_Found)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 241, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Error_Msg = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Error_Msg.setFont(font)
        self.Error_Msg.setStyleSheet("color: rgb(255, 0, 0);")
        self.Error_Msg.setAlignment(QtCore.Qt.AlignCenter)
        self.Error_Msg.setObjectName("Error_Msg")
        self.verticalLayout.addWidget(self.Error_Msg)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonBox.setFont(font)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Not_Found)
        self.buttonBox.clicked['QAbstractButton*'].connect(Not_Found.close)
        QtCore.QMetaObject.connectSlotsByName(Not_Found)

    def retranslateUi(self, Not_Found):
        _translate = QtCore.QCoreApplication.translate
        Not_Found.setWindowTitle(_translate("Not_Found", "Error"))
        self.Error_Msg.setText(_translate("Not_Found", "Address Not Found"))


